### ISSUE TITLE
header line adjustment

### ISSUE THREAD

**Issue by maxecharel** [ShuguangSun/ess-view-data#17]
ess-view-data is an amazing data viewer, however the header line does not seem to adjust to the user settings in terms of font size:
![header_bad_adjustment](https://user-images.githubusercontent.com/61969138/151758536-4eac0fca-67f7-4e77-b5ee-f69b1be382de.png)
Is there a way to adjust it, which would be really convenient when browsing big datasets?

**Comment by maxecharel** [comment]
Hi; looks like the problem has been solved... Have you made any change related to this issue? If not, the problem may come from my original config

**Comment by ShuguangSun** [comment]
It is not the issue of this package, but of the theme or Emacs at that time.  I have not change the code. I'm happy to hear it is resolved.

**Comment by maxecharel** [comment]
Nice, thanks. I haven't changed theme (vanilla Emacs, Doom theme) but I've changed font... Anyway, I close the issue :)
