### ISSUE TITLE
Data not printing

### ISSUE THREAD

**Issue by shirdekel** [ShuguangSun/ess-view-data#3]
I called `ess-view-data-print` on `mtcars` and got the following:

```
helm-M-x-execute-command: Cannot open load file: No such file or directory, csv-mode
```

Any ideas on how to further diagnose this?

**Comment by tmalsburg** [comment]
Not the author, but it seems that you have to install [csv-mode](https://elpa.gnu.org/packages/csv-mode.html) for this package to work.

@ShuguangSun, csv-mode is not declared as a dependency in the header.

**Comment by ShuguangSun** [comment]
csv-mode is required to make the head-line, that is, to show column names of data.frame to in the head-line.
I updated the dependency. Have a try.

Thanks @tmalsburg to point it out.

**Comment by shirdekel** [comment]
It works now, thanks!

**Comment by shirdekel** [comment]
To clarify, I still need to specify `csv-mode` in `init.el` (in my case in `dotspacemacs-additional-packages` because I use Spacemacs). But I don't need to add a `(require 'csv-mode)` anymore.
