### ISSUE TITLE
Support Vertico

### ISSUE THREAD

**Issue by fountainer** [ShuguangSun/ess-view-data#9]
I'm using the [Vertico](https://github.com/minad/vertico) for completion.  When selecting variables using function `ess-view-data-select`, the shortcut `C-j` cannot be used to finish input, because `C-j` goes to the next candidate in Vertico.

**Comment by ShuguangSun** [comment]
I can't replicate it. I tried it under Vertico, `C-j` works as expected. After `ess-view-data-select` and in the minibufer, I describe the key `C-h k C-j`, it tells the bindings to `icomplete-force-complete-and-exit`.

Are you using evil? Or you can help try the describe key approach and tell me the bindings.

**Comment by fountainer** [comment]
> I can't replicate it. I tried it under Vertico, `C-j` works as expected. After `ess-view-data-select` and in the minibufer, I describe the key `C-h k C-j`, it tells the bindings to `icomplete-force-complete-and-exit`.
> 
> Are you using evil? Or you can help try the describe key approach and tell me the bindings.

Yes. I'm using evil. `C-j` is bound to `vertico-next`.

**Comment by tpeacock19** [comment]
You need to use `vertico-exit-input`. I'm not sure what that is bound to in doom but it should allow you to exit.

Though I do think that `ess-view-data` as a whole should be compliant with `completing-read` and utilise `completing-read-mutliple` in these instances.

**Comment by fountainer** [comment]
> You need to use `vertico-exit-input`. I'm not sure what that is bound to in doom but it should allow you to exit.
> 
> Though I do think that `ess-view-data` as a whole should be compliant with `completing-read` and utilise `completing-read-mutliple` in these instances.

@tpeacock19 Thanks. `vertico-exit-input` (bound to `M-RET` in doom-emacs) works.  @ShuguangSun Please feel free to close it.
